### ISSUE TITLE
air-interface:loop-back-kind-on

### ISSUE THREAD

**Issue by demx8as6** [samans/draft-ybam-rfc8561bis#29]
In the excel spreadsheet line 99 is documented that the ONF air interface supports the configuration of a loopback.

```
  |  +--rw air-interface:loop-back-kind-on?                  loop-back-type
```

**Proposed solution:**

Add in the augmentation to the ietf-interface the following attribute

```
  |  +--rw mrl:loopback?                  loopback with if-feature loopback
```

Attribute description:
        "Maintenance Feature. The loopback function according to the chosen value. The default value is 'NONE'.";

Feature definition:

```
feature loopback {
  description 
    "Supports a maintenance feature maintenance feature to loop back local or remote signals";
}
```

The 'loopback' type should be defined as:

```
typedef loopback {
  type enumeration {

    enum NONE {
      description
        "The loopback function is disabled.";
    }

    enum REMOTE {
      description
        "Returning the signal of the remote site back to the remote site.";
    }

    enum LOCAL {
      description
        "Returning the signal of the local site back to the local site.";
    }

  }
  description 
    "Values describing the loopback function.";
}
```

**Comment by demx8as6** [comment]
copy yang from ietf git hub:
```
wget https://raw.githubusercontent.com/netmod-wg/interface-extensions-yang/master/ietf-if-extension@02023-01-26.yang
```

**Comment by DanielaSpreafico** [comment]
In the ietf-microwave-radio-link there are the mrl:if-loop and mrl:rf-loop attributes, both with direction informations (`client`, `radio`) as `local `or `remote `
What is the new requirement?

**Comment by samans** [comment]
Here is an SVG of the diagram we were talking about.  See if I got it right and if you like the formatting.  I started with ascii art and used aasvg to generate the SVG, so this will work in text and html/pdf versions.

![loopback](https://github.com/samans/draft-ybam-rfc8561bis/assets/8321265/7df1cb48-96c0-4535-b3b4-7651dc2f5534)

To resolve the use of ietf-if-extensions, we can evaluate the use of the loopback, but we need two loopbacks for one interface and the extension draft doesn't currently support that.

**Comment by demx8as6** [comment]
@samans : just a small remark/question: would it make sense to draw a box around Radio Unit and Modem Unit and label it with "ietf-interface"? This would clarify the fact that ietf-if-extension cannot be used.

**Comment by italobusi** [comment]
> To resolve the use of ietf-if-extensions, we can evaluate the use of the loopback, but we need two loopbacks for one interface and the extension draft doesn't currently support that.

While it is true that `ietf-if-extensions` does not support two loopbacks for one interface, IMHO, it would be possible to either:
1. update `ietf-if-extensions` to fix the issue in a generic way; 
2. provide some augmentations to the `ietf-if-extensions` in RFC8561-bis to resolve the gap for RLT interfaces

While exploring these options would have been my preference if we were defining the first version of RFC8561, considering that the `rf-loop` and `if-loop` are already defined in RFC8561, I think that before exploring these options, we need to check whether we agree on the value of deprecating the current solution in RFC8561-bis to reuse the `ietf-if-extensions`.

If there is no agreement to deprecate the current solution in RFC8561, IMHO, we can close the issue since the `rf-loop` and `if-loop` data nodes defined in RFC8561 are fulfilling the requirements.

My 2 cents

Italo

**Comment by samans** [comment]
I think it might be worth fixing ietf-if-extensions anyway.  I can talk to
Rob Wilton (the other author).  Then we can decide if we want to deprecate
rf-loop and if-loop.   Although, we will still need some kind of diagram.

**Comment by DanielaSpreafico** [comment]
My side I prefer to take as it is the the current solution in RFC8561. The loopback is correct and enough.

**Comment by samans** [comment]
Adding the documentation will make the if-loop and rf-loop easier to
understand.

**Comment by samans** [comment]
Add documentation, use diagram and keep the loopback as defined in the RFC.
